ALTER TABLE "OrderItem" ADD COLUMN "commissionRate" DOUBLE PRECISION NOT NULL DEFAULT 10;
ALTER TABLE "OrderItem" ADD COLUMN "commissionAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "vendorNetAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "payoutStatus" TEXT NOT NULL DEFAULT 'NOT_ELIGIBLE';

ALTER TABLE "Order" ADD COLUMN "subtotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "deliveryFee" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "paymentStatus" TEXT NOT NULL DEFAULT 'UNPAID';

CREATE TABLE "PlatformConfig" (
  "id" TEXT NOT NULL,
  "commissionRate" DOUBLE PRECISION NOT NULL DEFAULT 10,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PlatformConfig_pkey" PRIMARY KEY ("id")
);

INSERT INTO "PlatformConfig" ("id", "commissionRate", "updatedAt")
VALUES ('default', 10, CURRENT_TIMESTAMP);
